youtube:
  - channel: "https://www.youtube.com/c/galaxyproject"

    format: "🎥 New YouTube Video Released!\n\n{title}\n\n🔗 Watch it now: {link}"

    media:
      - bluesky
      - mastodon
      - matrix
      - slack

    mentions:
      bluesky:
        - galaxyproject.bsky.social
      mastodon:
        - galaxyfreiburg@bawü.social

    hashtags:
      bluesky:
        - usegalaxy
      mastodon:
        - usegalaxy
