name: Publish Content

on:
  pull_request_target:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run script to publish contents
        env:
          FEED_FILE: "feed.tml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -u app/feed_bot.py
