name: Create pr for youtube videos

on:
  schedule:
    - cron: "00 00 * * *"

  workflow_dispatch:

jobs:
  youtube-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: "arash77"
          repositories: "galaxy-social-main"


      - name: Run python script
        env:
          YOUTUBE_CONFIG_FILE: "app/youtube_config.yml"
          GALAXY_SOCIAL_BOT_TOKEN: ${{ steps.generate-token.outputs.token }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          REPO: "arash77/galaxy-social-main"
        run: python -u app/youtube_bot.py
